name: CI
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cpp-tests-ubuntu:
    name: 🇨‌ Test 🐧
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-24.04, ubuntu-24.04-arm]
        config: [Release]
        include:
          - runs-on: ubuntu-24.04
            config: Debug
    uses: ./.github/workflows/cpp-tests-ubuntu.yml
    with:
      runs-on: ${{ matrix.runs-on }}
      config: ${{ matrix.config }}
    secrets:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET || '' }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID || '' }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY || '' }}

  cpp-tests-macos:
    name: 🇨‌ Test 🍎
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macos-15-intel, macos-15]
        config: [Release]
        include:
          - runs-on: macos-15
            config: Debug
    uses: ./.github/workflows/cpp-tests-macos.yml
    with:
      runs-on: ${{ matrix.runs-on }}
      config: ${{ matrix.config }}
    secrets:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET || '' }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID || '' }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY || '' }}

  cpp-tests-windows:
    name: 🇨‌ Test 🏁
    strategy:
      fail-fast: false
      matrix:
        runs-on: [windows-2025, windows-11-arm]
        config: [Release]
        include:
          - runs-on: windows-2025
            config: Debug
    uses: ./.github/workflows/cpp-tests-windows.yml
    with:
      runs-on: ${{ matrix.runs-on }}
      config: ${{ matrix.config }}
    secrets:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET || '' }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID || '' }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY || '' }}
