name: 🇨 • Tests • windows
on:
  workflow_call:
    inputs:
      runs-on:
        description: >
          The Windows runner image to use. Defaults to 'windows-latest'.
          This can be any valid Windows runner image, such as 'windows-2022' or 'windows-2025'.
        default: "windows-latest"
        type: string
      config:
        description: >
          The build type to use. Defaults to 'Release'.
          This can be any valid CMake build type, such as 'Debug' or 'Release'.
        default: "Release"
        type: string
      device-arn:
        description: >
          The Amazon Braket device ARN to use for tests that require a quantum device.
          This can be any valid Amazon Braket device ARN, such as 'arn:aws:braket:::device/quantum-simulator/amazon/sv1'.
        default: "arn:aws:braket:::device/quantum-simulator/amazon/sv1"
        type: string
    secrets:
      AWS_S3_BUCKET:
        required: false
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

defaults:
  run:
    shell: pwsh

jobs:
  cpp-tests-windows:
    name: 🏁 ${{ inputs.runs-on }} ${{ inputs.config }}
    runs-on: ${{ inputs.runs-on }}
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      CTEST_PARALLEL_LEVEL: 4
      FORCE_COLOR: 3
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure CMake
        # automatically selects the MSVC compiler
        # AWS SDK C++ assume a Visual Studio generator
        run: |

          cmake -S . -B build `
            -G "Visual Studio 17 2022" `
            -A x64

      - name: Build
        env:
          CONFIG: ${{ inputs.config }}
        run: cmake --build build --config $env:CONFIG -- /m
      - name: Test
        env:
          CONFIG: ${{ inputs.config }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEVICE_ARN: ${{ inputs.device-arn }}
        run: |
          ctest -C $env:CONFIG --output-on-failure --test-dir build --repeat after-timeout:3 --timeout 600
