name: 📦 • Install and Test
on:
  workflow_call:
    inputs:
      runs-on:
        description: >
          The runner image to use.
        default: "ubuntu-latest"
        type: string

permissions:
  contents: read

jobs:
  cpp-tests-install:
    name: 📦 ${{ inputs.runs-on }}
    runs-on: ${{ inputs.runs-on }}
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      CTEST_PARALLEL_LEVEL: 4
      FORCE_COLOR: 3
    steps:
      # Very long directory paths can cause issues on Windows
      - name: Enable long paths on Windows and Git
        if: runner.os == 'Windows'
        run: |
          reg add HKLM\SYSTEM\CurrentControlSet\Control\FileSystem /v LongPathsEnabled /t REG_DWORD /d 1 /f
          git config --system core.longpaths true

      # Check out the repository
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      # Install build dependencies (Ubuntu only)
      - name: Install Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

      # Set up ccache for faster C++ builds
      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@a4d08616f5b614053bce228ddf881592f69d61d4 # v1.5.9
        with:
          prepend_symlinks_to_path: false
          override_cache_key: c++-tests-install-${{ inputs.runs-on }}
          windows_compile_environment: msvc

      # Set up mold as linker (Linux only)
      - name: Set up mold as linker
        uses: rui314/setup-mold@9c9c13bf4c3f1adef0cc596abc155580bcb04444 # v1

      # Build and install the Amazon Braket QDMI library
      - name: Configure CMake for QDMI
        run: >-
          cmake -S . -B install-build -DCMAKE_BUILD_TYPE=Release
          -DBUILD_AMAZON_BRAKET_TESTS=OFF

      - name: Build QDMI
        run: cmake --build install-build --config Release --target amazon-braket-qdmi-device

      - name: Install QDMI Runtime Component
        run: >
          cmake --install install-build --config Release
          --prefix install-dir
          --component amazon-braket-qdmi-device_Runtime

      - name: Install QDMI Development Component
        run: >
          cmake --install install-build --config Release
          --prefix install-dir
          --component amazon-braket-qdmi-device_Development

      # Build tests using the installed QDMI device library
      - name: Configure tests with the installed library
        run: >
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          -DUSE_INSTALLED_AMAZON_BRAKET_QDMI_DEVICE=ON
          -DBUILD_AMAZON_BRAKET_LIVE_TESTS=OFF
          -DCMAKE_PREFIX_PATH=install-dir

      - name: Build tests
        run: cmake --build build --config Release

      - name: Test
        run: ctest -C Release --output-on-failure --test-dir build --timeout 600
