name: 🇨 • Tests • windows
on:
  workflow_call:
    inputs:
      runs-on:
        description: >
          The Windows runner image to use. Defaults to 'windows-latest'.
          This can be any valid Windows runner image, such as 'windows-2022' or 'windows-2025'.
        default: "windows-latest"
        type: string
      config:
        description: >
          The build type to use. Defaults to 'Release'.
          This can be any valid CMake build type, such as 'Debug' or 'Release'.
        default: "Release"
        type: string
      device-arn:
        description: >
          The AWS Braket device ARN to use for tests that require a quantum device.
          This can be any valid AWS Braket device ARN, such as 'arn:aws:braket:::device/quantum-simulator/amazon/sv1'.
        default: "arn:aws:braket:::device/quantum-simulator/amazon/sv1"
        type: string
    secrets:
      AWS_S3_BUCKET:
        required: false
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

defaults:
  run:
    shell: pwsh

jobs:
  cpp-tests-windows:
    name: 🏁 ${{ inputs.runs-on }} ${{ inputs.config }}
    runs-on: ${{ inputs.runs-on }}
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      CTEST_PARALLEL_LEVEL: 4
      FORCE_COLOR: 3
    steps:
      # check out the repository (including submodules and all history)
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Configure CMake
        env:
          CONFIG: ${{ inputs.config }}
        # automatically selects the MSVC compiler
        run: |
          cmake -S . -B build `
            -G "Visual Studio 17 2022" `
            -A x64 `
            -DCMAKE_BUILD_TYPE=$env:CONFIG `
            -DCMAKE_COMPILE_WARNING_AS_ERROR=OFF `
            -DAWS_SDK_WARNINGS_ARE_ERRORS=OFF

      - name: Build
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        env:
          CONFIG: ${{ inputs.config }}
        with:
          timeout_minutes: 15
          max_attempts: 5
          shell: pwsh
          retry_on: error
          command: cmake --build build --config $env:CONFIG -- /m
      # run the tests (for retry for transient AWS connectivity failures)
      - name: Test
        env:
          CONFIG: ${{ inputs.config }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEVICE_ARN: ${{ inputs.device-arn }}
        run: |
          ctest -C $env:CONFIG --output-on-failure --test-dir build --timeout 600 --repeat after-timeout:3
