name: 🇨 • Coverage
on:
  workflow_call:
    inputs:
      device-arn:
        description: >
          The Amazon Braket device ARN to use for tests that require a quantum device.
          This can be any valid Amazon Braket device ARN, such as 'arn:aws:braket:::device/quantum-simulator/amazon/sv1'.
        default: "arn:aws:braket:::device/quantum-simulator/amazon/sv1"
        type: string
    secrets:
      AWS_S3_BUCKET:
        required: false
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-cpp-coverage
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  coverage:
    name: 📈 Coverage
    runs-on: ubuntu-24.04
    permissions:
      contents: read # Required for the `actions/checkout` action
      id-token: write # Required for the `codecov/codecov-action` action
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      CTEST_PARALLEL_LEVEL: 4
      FORCE_COLOR: 3
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false

      # set up ccache for faster builds
      - name: Set up ccache
        uses: Chocobo1/setup-ccache-action@802ec72ba1d54bbf75c52f45367253d6abec30f5 # v1.5.8
        with:
          prepend_symlinks_to_path: false
          override_cache_key: c++-coverage

      - name: Set up mold as linker
        uses: rui314/setup-mold@9c9c13bf4c3f1adef0cc596abc155580bcb04444 # v1

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: 3.13
          activate-environment: true
          enable-cache: true
          save-cache: ${{ github.ref == 'refs/heads/main' }}

      - name: Install Ninja
        run: uv tool install ninja

      # Install build dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON

      - name: Build
        run: cmake --build build --config Debug

      - name: Test
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEVICE_ARN: ${{ inputs.device-arn }}
        run: ctest -C Debug --output-on-failure --test-dir build --repeat until-pass:3 --timeout 600

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          fail_ci_if_error: true
          flags: cpp
          use_oidc: true
