name: 🇨 • Tests • macos
on:
  workflow_call:
    inputs:
      runs-on:
        description: >
          The macOS runner image to use. Defaults to 'macos-latest'.
          This can be any valid macOS runner image, such as 'macos-15' or 'macos-26'.
        default: "macos-latest"
        type: string
      config:
        description: >
          The build type to use. Defaults to 'Release'.
          This can be any valid CMake build type, such as 'Debug' or 'Release'.
        default: "Release"
        type: string

jobs:
  cpp-tests-macos:
    name: 🍎 ${{ inputs.runs-on }} ${{ inputs.config }}
    runs-on: ${{ inputs.runs-on }}
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      CTEST_PARALLEL_LEVEL: 4
      FORCE_COLOR: 3
    steps:
      # check out the repository
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      # Set up ccache for faster C++ builds
      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@a4d08616f5b614053bce228ddf881592f69d61d4 # v1.5.9
        with:
          prepend_symlinks_to_path: false
          override_cache_key: c++-tests-${{ inputs.runs-on }}-${{ inputs.config }}
      # configure CMake in the specified mode, optionally with additional arguments
      - name: Configure CMake
        env:
          CONFIG: ${{ inputs.config }}
        run: >-
          cmake -S . -B build -DCMAKE_BUILD_TYPE="$CONFIG"
          -DBUILD_AMAZON_BRAKET_LIVE_TESTS=OFF
      # build the project in the specified mode
      - name: Build
        run: cmake --build build
      # run the offline tests
      - name: Test
        run: ctest --output-on-failure --test-dir build --timeout 600
